version: "3.8"
services:
  db:
    image: postgres:16
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    # depends_on:
    #   - db
    network_mode: "host"
    # networks:
    #   - postgres-network

volumes:
  db:
    driver: local
networks:
  postgres-network:
    driver: bridge
